# Generated by Django 5.0.6 on 2024-08-31 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edit', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True, null=True)),
                ('title', models.CharField(max_length=40, unique=True)),
                ('content', models.TextField(blank=True, max_length=40)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_question', to='group.group')),
                ('like', models.ManyToManyField(blank=True, related_name='Question_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('content', models.TextField(blank=True, max_length=40)),
                ('like', models.ManyToManyField(blank=True, related_name='Answer_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_user', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='ask.question')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
