# Generated by Django 5.1 on 2024-08-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_answer_created_at_alter_question_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
