# Generated by Django 5.0.6 on 2024-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_alter_question_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, max_length=40000),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
