# Generated by Django 5.0.6 on 2024-09-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_alter_answer_content_alter_question_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
