# Generated by Django 5.0.6 on 2024-08-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
