# Generated by Django 5.0.6 on 2024-09-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=4000),
        ),
    ]
