# Generated by Django 5.1 on 2024-08-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_alter_question_options_alter_question_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'get_latest_by': 'created_at'},
        ),
    ]
