# Generated by Django 5.0.6 on 2024-09-13 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='blacklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
