# Generated by Django 5.0.6 on 2024-09-08 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmed_friend',
            field=models.ManyToManyField(blank=True, related_name='confirmed_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_friend',
            field=models.ManyToManyField(blank=True, related_name='waiting_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
