# Generated by Django 5.0.6 on 2024-09-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_created_at_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(choices=[('friend_accepted', 'friend_accepted'), ('friend_request', 'friend_request'), ('friend_message', 'friend_message'), ('group_joined', 'group_joined'), ('question_answered', 'question_answered'), ('question_liked', 'question_liked'), ('answer_liked', 'answer_liked')], max_length=50),
        ),
    ]
