# Generated by Django 5.0.6 on 2024-09-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='assets/avatar.svg', null=True, upload_to='profile_images/'),
        ),
    ]
